### Create employee
POST localhost:8080/api/v1/employees
Content-Type: application/json

{
  "firstName": "O'ktamov",
  "lastName": "Sardor",
  "phone": "998911576777",
  "email": "123456",
  "position": "BOSHMUTAXASSIS",
  "department": "DASTURCHILAR"

}

### Employee Get all
GET localhost:8080/api/v1/employees
Content-Type: application/json

### UPDATE employee
PUT localhost:8080/api/v1/employees/3
Content-Type: application/json

{
  "firstName": "Olim",
  "lastName": "Toshmatov",
  "phone": "998910000003",
  "email": "123456",
  "position": "BOSHMUTAXASSIS",
  "department": "DASTURCHILAR",
  "active": "true"

}

### Employee Delete By ID
DELETE localhost:8080/api/v1/employees/3
Content-Type: application/json

### Serch by name/surname
GET localhost:8080/api/v1/employees/search-all?name=to
Content-Type: application/json

### Filter by position
GET localhost:8080/api/v1/employees/filter-by-position?position=RAXBAR
Content-Type: application/json

### Filter by department
GET localhost:8080/api/v1/employees/filter-by-department?department=RAHBARIYAT
Content-Type: application/json