### Create Leave request
POST localhost:8080/api/v1/leaves
Content-Type: application/json
X-Auth-User-Id: 1

{
  "requestContent": "menga 2025 yil 26-noyabr kunidan navbatdagi mehnat ta'tilga chiqishimga ruxsat berishingizni so'rayman",
  "leaveType": "YILLIK",
  "startDate": "2025-11-26",
  "endDate": "2025-11-30"
}

### Arizani tasdiqlash
PUT localhost:8080/api/v1/leaves/2/approve
Content-Type: application/json
X-Auth-User-Id: 2

### Arizani RAD qilish (URLga ariza ID si kiritiladi)
PUT localhost:8080/api/v1/leaves/3/reject
Content-Type: text/plain
X-Auth-User-Id: 2

Ish xajmi ortganligi sababli ta'til keyinga qoldirildi

### xodim o'zini arizalarini ko'rishi
GET http://localhost:8080/api/v1/leaves/my-requests
Content-Type: application/json
X-Auth-User-Id: 3

### Employee Balance checking  ID-xodimniki
GET localhost:8080/api/v1/leaves/3/balance

### RAXBAR UCHUN TASDIQLASHGA KUTILAYOTGAN ARIZALAR RO'YXATI (Raxbar ID = X-Auth-User-Id)
GET localhost:8080/api/v1/leaves/pending
Content-Type: application/json
X-Auth-User-Id: 2